### PR TITLE
Update tool-Docker-action to v2.1.0

### PR DESCRIPTION
**Pull request by nwiltsie**
This PR updates the `tool-Docker-action` Action to version 2.1.0. There are a few big changes in this version:

1. Pushing to any branch `foo` will [build this repository's image](https://github.com/uclahs-cds/tool-Docker-action/pull/14) and tag it as `branch-foo`. That tagged image will be removed when the branch is deleted.
1. By default the Action will only build [SemVer](https://semver.org/) tags (e.g. `v1.2.3-xxx`). Repositories that need to use other kinds of tags (e.g. `v1.2beta`) can pass the optional `non-semver-tags` argument; doing so will build all tags that begin with `v`.

There are a bunch of smaller changes buried in there - you can see them all at [this link](https://github.com/uclahs-cds/tool-Docker-action/compare/ebe9f1c...v2.1.0).

Based on this repository's existing tags, I've determined that it _does_ follow semantic versioning. The updated workflow therefore does _not_ pass the `non-semver-tags` argument to the Action, although it can be uncommented in the future if need be.

### CODE REVIEW

**Review by Faizal-Eeman — APPROVED** [review]
Looks good!

**Comment by nwiltsie** [comment]
Something's wonky here - the image isn't building correctly in this branch _or_ on `main`. See #22.

**Comment by nwiltsie** [comment]
Okay @Faizal-Eeman, I think that I've got the build repaired.

1. I switched the base image from `r-base` to `rocker/r-ver` because the former is not version-pinned (see https://github.com/rocker-org/rocker/issues/540#issuecomment-1952455816).
2. `r-base` installs R into `/usr/lib` while `r-ver` installs it into `/usr/local/lib`, so I messed with the `library` logic (a0c4bc4832ee4ec8bae9c54816f04d998e79dc54) and it seems to work now.

Sanity-checking that, the `install.packages` command [installs](https://github.com/uclahs-cds/docker-Battenberg/actions/runs/10425215742/job/28875620612?pr=21#step:3:805) into `/usr/local/lib/R/site-library...`:

> 0.394 > install.packages(c("argparse", "BiocManager", "pkgdepends", "optparse"))
> 0.397 Installing packages into ‘/usr/local/lib/R/site-library’
> 0.397 (as ‘lib’ is unspecified)

So does the `BiocManager::install` [command](https://github.com/uclahs-cds/docker-Battenberg/actions/runs/10425215742/job/28875620612?pr=21#step:3:1406) (I added some bold emphasis):

> 18.00 Bioconductor version 3.19 (BiocManager 1.30.23), R 4.4.1 (2024-06-14)
> 18.00 Installing package(s) 'BiocVersion', 'ellipsis', 'VariantAnnotation'
> 18.34 also installing the dependencies ‘formatR’, ‘glue’, ‘lifecycle’, ‘fastmap’, ‘sys’, ‘lambda.r’, ‘futile.options’, ‘bit’, ‘vctrs’, ‘cachem’, ‘askpass’, ‘abind’, ‘SparseArray’, ‘futile.logger’, ‘snow’, ‘BH’, ‘cpp11’, ‘bit64’, ‘blob’, ‘memoise’, ‘pkgconfig’, ‘plogr’, ‘png’, ‘mime’, ‘openssl’, ‘RCurl’, ‘rjson’, ‘yaml’, ‘matrixStats’, ‘UCSC.utils’, ‘GenomeInfoDbData’, ‘S4Arrays’, ‘DelayedArray’, ‘bitops’, ‘BiocParallel’, ‘crayon’, ‘RSQLite’, ‘KEGGREST’, ‘XML’, ‘httr’, ‘GenomicAlignments’, ‘BiocIO’, ‘restfulr’, ‘rlang’, ‘BiocGenerics’, ‘MatrixGenerics’, ‘GenomeInfoDb’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘Rsamtools’, ‘DBI’, ‘**zlibbioc**’, ‘Biobase’, ‘S4Vectors’, ‘IRanges’, ‘XVector’, ‘Biostrings’, ‘AnnotationDbi’, ‘rtracklayer’, ‘BSgenome’, ‘GenomicFeatures’, ‘Rhtslib’

> 62.18 * installing *source* package ‘**zlibbioc**’ ...
> 62.18 ** using staged installation
> 62.52 configure: creating ./config.status
> 62.60 config.status: creating src/Makevars
> 62.64 ** libs
> 62.65 using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
> 62.65 mkdir -p "/usr/local/lib/R/site-library/00LOCK-zlibbioc/00new/zlibbioc/include"
> 62.66 gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c R_init_zlibbioc.c -o R_init_zlibbioc.o
> 62.67 gcc -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o zlibbioc.so R_init_zlibbioc.o -L/usr/local/lib/R/lib -lR
> 62.68 installing to **/usr/local/lib/R/site-library**/00LOCK-zlibbioc/00new/zlibbioc/libs

The `installer.R` logs don't report the installation path, but the docker image itself shows that `Battenberg` was installed to `/usr/local/lib/R/site-library`:

```console
$ docker run -it ghcr.io/uclahs-cds/battenberg:branch-nwiltsie_update_docker_action ls -1 /usr/local/lib/R/site-library/Battenberg
DESCRIPTION
example
extdata
help
html
INDEX
LICENSE
Meta
NAMESPACE
R
TODO

**Comment by Faizal-Eeman** [comment]
> The installer.R logs don't report the installation path, but the docker image itself shows that Battenberg was installed to /usr/local/lib/R/site-library:
> docker run -it ghcr.io/uclahs-cds/battenberg:branch-nwiltsie_update_docker_action ls -1 /usr/local/lib/R/site-library/Battenberg

Yup, tested the above command and confirming Battenberg is available in `/usr/local/lib/R/site-library`

**Review by Faizal-Eeman — APPROVED** [review]

**Comment by Faizal-Eeman** [comment]
Thanks a lot @nwiltsie. I'm merging this PR.

**Pull request merged**
